CREATE TABLE IF NOT EXISTS subscription (
    sub_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    symbol VARCHAR(10),
    price DOUBLE PRECISION,
    indicator VARCHAR(10)
);